version: 2

sources:
  - name: dbwarehouse_wlm7
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contém dados históricos de commodities"
        columns:
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço de fechamento da commodity"
          - name: symbol
            description: "Símbolo da commodity"

      - name: commodities_moviment
        description: "Tabela seed"
        columns:
          - name: date
            description: "Data da transação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo de transação (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"