version: 2

models:
  - name: dm_commodities
    description: "Datamart para dados de commodities integrados com movimentações"
    columns:
      - name: date
        description: "Data da observação"
      - name: symbol
        description: "Símbolo da commodity"
      - name: close_value
        description: "Preço de fechamento da commodity"
      - name: action
        description: "Tipo de transação (buy/sell)"
      - name: quantity
        description: "Quantidade transacionada"
      - name: valor
        description: "Valor da transação"
      - name: ganho
        description: "Ganho ou perda da transação"